name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [ dev ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testing with pytest
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t nogorka42/parcel-lockers .
          docker push nogorka42/parcel-lockers

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "SSH login successful"
            
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            docker pull nogorka42/parcel-lockers
            
            docker stop parcel-lockers || true
            docker rm parcel-lockers || true
            
            docker run --name parcel-lockers -d -p 3000:80 \
              -v /etc/letsencrypt/live/nogorka42.ru/fullchain.pem:/fullchain.pem \
              -v /etc/letsencrypt/live/nogorka42.ru/privkey.pem:/privkey.pem \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              nogorka42/parcel-lockers
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
