name: Python FastAPI CI/CD

on:
  push:
    branches: [server]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint  # Ensure pylint is installed

      - name: Lint with Pylint
        run: |
          # Run pylint on all python files within the src directory
          pylint $(find . -type f -name "*.py")


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip "cd /path/to/your/app && git pull && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
